# fly.toml app configuration file generated for ankaa-sim-withered-frog-8614 on 2025-11-05T23:32:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iot-mock'
primary_region = 'dfw'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
